# Generated by Django 3.1.2 on 2020-10-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('sub_plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_duration', models.IntegerField(max_length=4)),
                ('plan_cost', models.IntegerField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Subscription Plan',
            },
        ),
    ]
