# Generated by Django 3.1.2 on 2020-10-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('sub_plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_duration', models.IntegerField()),
                ('plan_cost', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Subscription Plan',
            },
        ),
    ]
