# Generated by Django 3.1.2 on 2020-10-25 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_auto_20201014_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomControl',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='', max_length=250, null=True)),
                ('host_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='host_user', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='room_members', to=settings.AUTH_USER_MODEL)),
                ('pending_request', models.ManyToManyField(related_name='pending_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Room Controls',
            },
        ),
        migrations.CreateModel(
            name='UserRoomDetails',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.customuser')),
                ('pending_request', models.ManyToManyField(related_name='pending_room_request', to=settings.AUTH_USER_MODEL)),
                ('user_rooms', models.ManyToManyField(to='room.RoomControl')),
            ],
            options={
                'verbose_name_plural': 'User Room Details',
            },
        ),
    ]
