# Generated by Django 3.1.2 on 2020-10-27 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRoomDetails',
        ),
    ]
