# Generated by Django 3.1.2 on 2020-10-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201002_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('A', 'Admin'), ('P', 'Provider'), ('U', 'User')], default='User', max_length=1),
        ),
    ]
