# Generated by Django 3.1.2 on 2020-10-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201014_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('U', 'User'), ('P', 'Provider'), ('A', 'Admin')], max_length=1),
        ),
    ]
