# Generated by Django 3.1.2 on 2020-10-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesdetails',
            name='thumbnail_image',
            field=models.IntegerField(),
        ),
    ]
