# Generated by Django 3.1.2 on 2020-10-08 19:22

from django.db import migrations, models
import provider.models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_auto_20201009_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesdetails',
            name='thumbnail_image',
            field=models.ImageField(upload_to=provider.models.series_thumbnail_directory_path),
        ),
    ]
