# Generated by Django 3.1.2 on 2020-10-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_auto_20201009_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesseasondetails',
            name='thumbnail_image',
            field=models.IntegerField(),
        ),
    ]
