# Generated by Django 3.1.2 on 2020-10-08 19:26

from django.db import migrations, models
import provider.models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_auto_20201009_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesseasondetails',
            name='thumbnail_image',
            field=models.ImageField(upload_to=provider.models.series_season_thumbnail_directory_path),
        ),
    ]
