# Generated by Django 3.1.2 on 2020-10-08 19:29

from django.db import migrations, models
import provider.models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0006_auto_20201009_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freemovievideo',
            name='thumbnail_image',
            field=models.ImageField(upload_to=provider.models.video_thumbnail_directory_path),
        ),
        migrations.AlterField(
            model_name='freeseriesvideos',
            name='thumbnail_image',
            field=models.ImageField(upload_to=provider.models.video_thumbnail_directory_path),
        ),
        migrations.AlterField(
            model_name='moviedetails',
            name='thumbnail_image',
            field=models.ImageField(upload_to=provider.models.movie_thumbnail_directory_path),
        ),
        migrations.AlterField(
            model_name='movievideo',
            name='thumbnail_image',
            field=models.ImageField(upload_to=provider.models.video_thumbnail_directory_path),
        ),
        migrations.AlterField(
            model_name='seriesvideos',
            name='thumbnail_image',
            field=models.ImageField(upload_to=provider.models.video_thumbnail_directory_path),
        ),
    ]
