# Generated by Django 3.1.2 on 2020-10-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0007_auto_20201009_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='freemovievideo',
            name='extension',
            field=models.PositiveSmallIntegerField(choices=[(1, 'mp4'), (2, 'mkv'), (3, 'flv'), (4, 'webm'), (5, 'ogg')], default=1),
        ),
        migrations.AddField(
            model_name='freeseriesvideos',
            name='extension',
            field=models.PositiveSmallIntegerField(choices=[(1, 'mp4'), (2, 'mkv'), (3, 'flv'), (4, 'webm'), (5, 'ogg')], default=1),
        ),
        migrations.AddField(
            model_name='movievideo',
            name='extension',
            field=models.PositiveSmallIntegerField(choices=[(1, 'mp4'), (2, 'mkv'), (3, 'flv'), (4, 'webm'), (5, 'ogg')], default=1),
        ),
        migrations.AddField(
            model_name='seriesvideos',
            name='extension',
            field=models.PositiveSmallIntegerField(choices=[(1, 'mp4'), (2, 'mkv'), (3, 'flv'), (4, 'webm'), (5, 'ogg')], default=1),
        ),
    ]
