# Generated by Django 3.1.2 on 2020-10-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0010_history_movierating_seriesrating_videocomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocomment',
            name='comment_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'positive'), (2, 'negative')], default=1),
        ),
    ]
