# Generated by Django 3.1.2 on 2020-10-27 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('provider', '0011_videocomment_comment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_val', models.PositiveSmallIntegerField(choices=[(1, 'Violent or repulsive content'), (2, 'Hateful or abusive content'), (3, 'Harmful or dangerous act'), (4, 'Sexual content'), (5, 'Child abuse'), (6, 'Promotes terrorism'), (7, 'Spam or misleading'), (8, 'Infringes my rights'), (9, 'Captions issue')], default=1)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='provider.videos')),
            ],
            options={
                'verbose_name_plural': 'Report Video',
            },
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_val', models.PositiveSmallIntegerField(choices=[(1, 'Unwanted commercial content or spam'), (2, 'Sexually explicit material'), (3, 'Unwanted commercial content or spam'), (4, 'Sexually explicit material'), (5, 'Unwanted commercial content or spam')], default=1)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='provider.videocomment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Report Comment',
            },
        ),
    ]
