# Generated by Django 3.1.2 on 2020-10-27 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('provider', '0012_reportcomment_reportvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcomment',
            name='flag_val',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Unwanted commercial content or spam'), (2, 'Sexually explicit material'), (3, 'Child abuse'), (4, 'Hate speech or graphic violence'), (5, 'Harassment or bullying')], default=1),
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(related_name='favourites', to=settings.AUTH_USER_MODEL)),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='provider.videos')),
            ],
            options={
                'verbose_name_plural': 'Favourites',
            },
        ),
    ]
