# Generated by Django 3.1.2 on 2020-10-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0013_auto_20201027_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocomment',
            name='comment_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'positive'), (2, 'negative'), (3, 'neutral')], default=1),
        ),
    ]
