# Generated by Django 3.1.2 on 2020-10-04 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscribe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, default='', max_length=100)),
                ('transaction_start_time', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.CharField(choices=[('C', 'Card'), ('W', 'Wallet')], max_length=1)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Credit'), (2, 'Failed'), (3, 'Pending'), (4, 'Sent'), (5, 'Completed')])),
                ('sub_plan_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscribe.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transaction Details',
            },
        ),
    ]
