# Generated by Django 3.1.2 on 2020-10-02 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscribe', '0002_auto_20201002_1537'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_time', models.DateTimeField()),
                ('payment_type', models.CharField(choices=[('C', 'Card'), ('W', 'Wallet')], max_length=1)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Credit'), (2, 'Failed'), (3, 'Pending'), (4, 'Sent'), (5, 'Completed')])),
                ('sub_plan_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscribe.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transaction Details',
            },
        ),
    ]
