# Generated by Django 3.1.2 on 2020-10-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
