# Generated by Django 3.1.2 on 2020-10-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_transactiontoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontoken',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Failed'), (2, 'Credit')], default=1),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Failed'), (2, 'Pending'), (3, 'Sent'), (4, 'Completed')]),
        ),
    ]
