# Generated by Django 3.1.2 on 2020-10-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20201004_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetails',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Failed'), (2, 'Pending'), (3, 'Sent'), (4, 'Completed'), (5, 'Credit')]),
        ),
    ]
