# Generated by Django 3.1.2 on 2020-10-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_auto_20201004_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontoken',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Failed'), (2, 'Credit'), (3, 'Refunded')], default=1),
        ),
    ]
