# Generated by Django 3.1.2 on 2020-10-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_auto_20201004_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetails',
            name='transaction_start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transactiontoken',
            name='transaction_end_time',
            field=models.DateTimeField(),
        ),
    ]
