# Generated by Django 3.1.2 on 2020-10-05 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0007_auto_20201005_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMoneyTransactionDetails',
            fields=[
                ('transaction_id', models.CharField(blank=True, default='', max_length=100, primary_key=True, serialize=False)),
                ('transaction_start_time', models.DateTimeField()),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Failed'), (2, 'Pending'), (3, 'Sent'), (4, 'Completed'), (5, 'Credit')])),
                ('payment_id', models.CharField(blank=True, default='', max_length=100)),
                ('transaction_end_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Add Money Transaction Details',
            },
        ),
    ]
