# Generated by Django 3.1.2 on 2020-10-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_remove_addmoneytransactiondetails_transaction_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmoneytransactiondetails',
            name='transaction_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='transaction_amount',
            field=models.IntegerField(default=0),
        ),
    ]
