# Generated by Django 3.1.2 on 2020-11-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_auto_20201005_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmoneytransactiondetails',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Failed'), (2, 'Pending'), (3, 'Sent'), (4, 'Completed'), (5, 'Credit'), (6, 'Refunded')]),
        ),
    ]
